### ISSUE TITLE
Discovering causal signals in images

### ISSUE THREAD

**Issue by vipulbjj** [lopezpaz/causation_learning_theory#1]
@lopezpaz Great work. Can you please share the code for your other paper "Discovering causal signals in images" too? 
It would be of great help.

**Comment by siddsuresh97** [comment]
Hey @vipulbjj did you get the code for the paper yet?

**Comment by lopezpaz** [comment]
Dear all,

Unfortunately, I have no access to such code anymore.

Best,
dlp.

**Comment by AlexDrBanana** [comment]
@vipulbjj Did you by any chance manage to reproduce the results?
